#!/bin/bash

function get_temp {
    echo "$(( $1 / 1000 ))"
}

function find_hwmon {
    for i in /sys/class/hwmon/hwmon*/name; do
        if [ "$(cat $i)" = "$1" ]; then
            echo $(dirname $i)
            return
        fi
    done
}

# If the first argument is equal to "-h" or "--help"
# list all the possible sensors.
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    for i in /sys/class/hwmon/hwmon*/name; do
        echo "SENSOR_CHIP=$(cat $i)"
        for j in $(dirname $i)/temp*_input; do
            echo "  SENSOR_NUM=$(basename $j | tr -cd '[0-9]'), temperature: $(get_temp $(cat $j))"
        done
    done
    exit 0
fi

# If SENSOR_CHIP is not set, use the first sensor.
if [ -z "$SENSOR_CHIP" ]; then
    SENSOR_CHIP=$(cat /sys/class/hwmon/hwmon*/name | head -n 1)
fi

SENSOR_NUM=${SENSOR_NUM:-1}
T_WARN=${T_WARN:-70}
T_CRIT=${T_CRIT:-90}
COLOR_WARN=${COLOR_WARN:-"#FFCC00"}
COLOR_CRIT=${COLOR_CRIT:-"#FF0000"}

temperature=$(get_temp $(cat $(find_hwmon $SENSOR_CHIP)/temp${SENSOR_NUM}_input))
echo "$temperature°C" # short text
echo "$temperature°C" # long text

if [ "$temperature" -ge "$T_CRIT" ]; then
    echo "$COLOR_CRIT"
elif [ "$temperature" -ge "$T_WARN" ]; then
    echo "$COLOR_WARN"
fi
